### ISSUE TITLE
Implement clipping in the visualization

### ISSUE THREAD

**Issue by lobis** [mipt-npm/visionforge#36]
Implement a clipping option in the rendering, like it is done in the ROOT Event Viewer.

There should be options to choose between an infinite plane and a box, which could be translated using the mouse along the three coordinate axis.

**Comment by altavir** [comment]
ThreeJs has this option: https://threejs.org/docs/#api/en/materials/Material.clippingPlanes
https://threejs.org/examples/#webgl_clipping_intersection

I will try to add it to scene controls.

**Comment by altavir** [comment]
Basic 3-axis clipping implemented in Three-JS via sliders on Canvas controls. More advanced controls could be added later.
